{% set name = "txl-remote-terminals" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txl_remote_terminals-{{ version }}.tar.gz
  sha256: c662128e10c6449e05601f0cdb9b2fc76aa1107de73a741c6ed2719dd99dd598

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl
    - httpx >=0.23.1
    - httpx-ws >=0.4.2

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_remote_terminals

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/remote_terminals
  summary: TXL plugin for remote terminals
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/remote_terminals
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
