{% set python_min = "3.10" %}
{% set name = "txl-remote-terminals" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_remote_terminals-{{ version }}.tar.gz
  sha256: b6ce892f44c3ebb7a34d4aafee12d9fd81906922d69f0c37eb58557655acae98

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl =0.3.2
    - httpx >=0.23.1
    - httpx-ws >=0.4.2

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - txl_remote_terminals

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/remote_terminals
  summary: TXL plugin for remote terminals
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/remote_terminals
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
